robot: "fox"
port: "/dev/ttyTHS1"
baudrate: 115200
kinematics_mode: 5
wheel_radius: 0.04
wheel_separation_x: 0.295
wheel_separation_y: 0.306
motors_index: [0, 1, 2, 3]
motors_signs: [-1.0, -1.0, -1.0, -1.0]
odom_frame: "odom"
base_frame: "base_footprint"
max_vel_x: 0.8
max_vel_y: 0.8
max_vel_th: 1.5
publish_odom: true
publish_odom_tf: true